System.InvalidOperationException: 对象的当前状态使该操作无效。
   在 Reflector.Disassembler.TranslatorBase.TranslationResultsCreator.AddToGroups(TranslationResult tr, IBlockStatement block, String nextLabel)
   在 Reflector.Disassembler.TranslatorBase.TryResult.Complete()
   在 Reflector.Disassembler.TranslatorBase.TryResult.SelfOptimize()
   在 Reflector.Disassembler.TranslatorBase.TranslationResult.Optimize()
   在 Reflector.Disassembler.TranslatorBase.IndexSwitchResult.Rebuild()
   在 Reflector.Disassembler.TranslatorBase.IndexSwitchResult.SelfOptimize()
   在 Reflector.Disassembler.TranslatorBase.TranslationResult.Optimize()
   在 Reflector.Disassembler.TranslatorBase.CodeResult.SelfOptimize()
   在 Reflector.Disassembler.TranslatorBase.TranslationResult.Optimize()
   在 Reflector.Disassembler.TranslatorBase.ConditionalResult.Complete()
   在 Reflector.Disassembler.TranslatorBase.ConditionalResult.SelfOptimize()
   在 Reflector.Disassembler.TranslatorBase.TranslationResult.Optimize()
   在 Reflector.Disassembler.TranslatorBase.CodeResult.SelfOptimize()
   在 Reflector.Disassembler.TranslatorBase.TranslationResult.Optimize()
   在 Reflector.Disassembler.TranslatorBase.CodeResult.SelfOptimize()
   在 Reflector.Disassembler.TranslatorBase.TranslationResult.Optimize()
   在 Reflector.Disassembler.TranslatorBase.ConditionalResult.Complete()
   在 Reflector.Disassembler.TranslatorBase.ConditionalResult.SelfOptimize()
   在 Reflector.Disassembler.TranslatorBase.TranslationResult.Optimize()
   在 Reflector.Disassembler.TranslatorBase.LoopResult.Rebuild()
   在 Reflector.Disassembler.TranslatorBase.LoopResult.SelfOptimize()
   在 Reflector.Disassembler.TranslatorBase.TranslationResult.Optimize()
   在 Reflector.Disassembler.TranslatorBase.ReferenceResult.SelfOptimize()
   在 Reflector.Disassembler.TranslatorBase.TranslationResult.Optimize()
   在 Reflector.Disassembler.TranslatorBase.CodeResult.SelfOptimize()
   在 Reflector.Disassembler.TranslatorBase.TranslationResult.Optimize()
   在 Reflector.Disassembler.TranslatorBase.TryResult.Complete()
   在 Reflector.Disassembler.TranslatorBase.TryResult.SelfOptimize()
   在 Reflector.Disassembler.TranslatorBase.TranslationResult.Optimize()
   在 Reflector.Disassembler.TranslatorBase.CodeResult.SelfOptimize()
   在 Reflector.Disassembler.TranslatorBase.TranslationResult.Optimize()
   在 Reflector.Disassembler.TranslatorBase.TranslationResultsCreator.Optimize()
   在 Reflector.Disassembler.NewTranslator.TranslateMethodDeclaration(IMethodDeclaration mD, IMethodBody mB)
   在 Reflector.Disassembler.Disassembler.TransformMethodDeclaration(IMethodDeclaration value)
   在 Reflector.CodeModel.Visitor.Transformer.TransformMethodDeclarationCollection(IMethodDeclarationCollection methods)
   在 Reflector.Disassembler.Disassembler.TransformTypeDeclaration(ITypeDeclaration value)
   在 Reflector.Application.Translator.TranslateTypeDeclaration(ITypeDeclaration value, Boolean memberDeclarationList, Boolean methodDeclarationBody)
   在 Reflector.Application.FileDisassembler.WriteTypeDeclaration(ITypeDeclaration typeDeclaration, String sourceFile, ILanguageWriterConfiguration languageWriterConfiguration)
namespace VRage.Compiler
{
}

