namespace DShowNET
{
    using System;

    public enum DsEvCode
    {
        None = 0,
        Complete = 1,
        UserAbort = 2,
        ErrorAbort = 3,
        Time = 4,
        Repaint = 5,
        StErrStopped = 6,
        StErrStPlaying = 7,
        ErrorStPlaying = 8,
        PaletteChanged = 9,
        VideoSizeChanged = 10,
        QualityChange = 11,
        ShuttingDown = 12,
        ClockChanged = 13,
        Paused = 14,
        OpeningFile = 0x10,
        BufferingData = 0x11,
        FullScreenLost = 0x12,
        Activate = 0x13,
        NeedRestart = 20,
        WindowDestroyed = 0x15,
        DisplayChanged = 0x16,
        Starvation = 0x17,
        OleEvent = 0x18,
        NotifyWindow = 0x19,
        DvdDomChange = 0x101,
        DvdTitleChange = 0x102,
        DvdChaptStart = 0x103,
        DvdAudioStChange = 260,
        DvdSubPicStChange = 0x105,
        DvdAngleChange = 0x106,
        DvdButtonChange = 0x107,
        DvdValidUopsChange = 0x108,
        DvdStillOn = 0x109,
        DvdStillOff = 0x10a,
        DvdCurrentTime = 0x10b,
        DvdError = 0x10c,
        DvdWarning = 0x10d,
        DvdChaptAutoStop = 270,
        DvdNoFpPgc = 0x10f,
        DvdPlaybRateChange = 0x110,
        DvdParentalLChange = 0x111,
        DvdPlaybStopped = 0x112,
        DvdAnglesAvail = 0x113,
        DvdPeriodAStop = 0x114,
        DvdButtonAActivated = 0x115,
        DvdCmdStart = 0x116,
        DvdCmdEnd = 0x117,
        DvdDiscEjected = 280,
        DvdDiscInserted = 0x119,
        DvdCurrentHmsfTime = 0x11a,
        DvdKaraokeMode = 0x11b
    }
}

