namespace VRage.Utils
{
    using System;

    public enum MyGuiDrawAlignEnum
    {
        HORISONTAL_LEFT_AND_VERTICAL_TOP,
        HORISONTAL_LEFT_AND_VERTICAL_CENTER,
        HORISONTAL_LEFT_AND_VERTICAL_BOTTOM,
        HORISONTAL_CENTER_AND_VERTICAL_TOP,
        HORISONTAL_CENTER_AND_VERTICAL_CENTER,
        HORISONTAL_CENTER_AND_VERTICAL_BOTTOM,
        HORISONTAL_RIGHT_AND_VERTICAL_TOP,
        HORISONTAL_RIGHT_AND_VERTICAL_CENTER,
        HORISONTAL_RIGHT_AND_VERTICAL_BOTTOM
    }
}

